packages:
  - activities/**
  - adapters/**
  - apps/**
  - configs/**
  - contracts/**
  - onboarding/**
  - packages/**
  - scripts/**
  - clusters/**
  - tools/**
  - tooling-configs/**
  - views/**
  - workflows/**
  - '!**/cdk.out/**'
  - '!**/debug_info/**'
catalogs:
  default:
    '@eslint/js': ^9.37.0
    '@jest/globals': ^29.7.0
    '@types/command-line-args': ^5.0.0
    '@types/command-line-usage': ^5.0.1
    '@types/jest': ^29.5.14
    '@types/js-yaml': 4.0.9
    '@types/node': ^22.18.6
    '@types/react': 19.2.6
    '@types/react-dom': 19.2.3
    '@types/semver': ^7.5.4
    '@types/string-format': ^2.0.0
    '@typescript-eslint/eslint-plugin': ^8.31.1
    '@typescript-eslint/parser': ^8.31.1
    chalk: ^5.0.0
    chokidar: ^3.6.0
    command-line-args: ^5.1.1
    command-line-usage: ^6.1.0
    commander: 13.1.0
    depcheck: ^1.4.3
    es-toolkit: ^1.39.10
    eslint: ^9.17.0
    eslint-config-prettier: ^10.1.2
    eslint-config-turbo: ^2.5.8
    eslint-plugin-only-warn: 1.1.0
    eslint-plugin-simple-import-sort: 12.1.1
    espree: ^10.3.0
    glob: ^10.3.10
    globals: ^16.4.0
    handlebars: 4.7.8
    ignore: ^7.0.5
    isomorphic-git: 1.30.1
    jest: ^29.7.0
    js-yaml: 4.1.0
    p-limit: ^6.1.0
    prettier: 3.5.3
    prettier-plugin-packagejson: 2.5.19
    prettier-plugin-solidity: 2.1.0
    prettier-plugin-tailwindcss: 0.6.8
    semver: ^7.5.4
    string-format: ^2.0.0
    toml: ^3.0.0
    ts-jest: ^29.3.1
    tsup: ^8.4.0
    tsx: ^4.19.3
    turbo: ^2.4.4
    typescript: ^5.8.2
    vitest: ^3.2.3
    zod: 4.3.5
    zx: ^8.8.5
  react19:
    '@types/react': 19.2.6
    '@types/react-dom': 19.2.3
cleanupUnusedCatalogs: true
disallowWorkspaceCycles: true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@layerzerolabs/*'
onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
