packages:
  - activities/**
  - adapters/**
  - apps/**
  - configs/**
  - contracts/**
  - onboarding/**
  - packages/**
  - scripts/**
  - clusters/**
  - tools/**
  - tooling-configs/**
  - views/**
  - workflows/**
  - '!**/cdk.out/**'
  - '!**/debug_info/**'
catalogs:
  default:
    '@codama/nodes-from-anchor': 1.2.9
    '@codama/renderers-js-umi': 1.1.23
    '@eslint/js': ^9.37.0
    '@ethersproject/abstract-signer': ^5.8.0
    '@ethersproject/bytes': ^5.8.0
    '@jest/globals': ^29.7.0
    '@solana/web3.js': ^1.95.8
    '@types/command-line-args': ^5.0.0
    '@types/command-line-usage': ^5.0.1
    '@types/jest': ^29.5.14
    '@types/js-yaml': 4.0.9
    '@types/node': ^22.18.6
    '@types/react': 19.2.6
    '@types/react-dom': 19.2.3
    '@types/semver': ^7.5.4
    '@types/string-format': ^2.0.0
    '@typescript-eslint/eslint-plugin': ^8.31.1
    '@typescript-eslint/parser': ^8.31.1
    chalk: ^5.0.0
    chokidar: ^3.6.0
    codama: 1.3.7
    command-line-args: ^5.1.1
    command-line-usage: ^6.1.0
    commander: 13.1.0
    depcheck: ^1.4.3
    dotenv: 16.4.5
    es-toolkit: ^1.39.10
    eslint: ^9.17.0
    eslint-config-prettier: ^10.1.2
    eslint-config-turbo: ^2.5.8
    eslint-plugin-only-warn: 1.1.0
    eslint-plugin-simple-import-sort: 12.1.1
    espree: ^10.3.0
    ethers: ^5.8.0
    glob: ^10.3.10
    globals: ^16.4.0
    handlebars: 4.7.8
    ignore: ^7.0.5
    isomorphic-git: 1.30.1
    jest: ^29.7.0
    js-yaml: 4.1.0
    merkletreejs: ^0.3.11
    p-limit: ^6.1.0
    prettier: 3.5.3
    prettier-plugin-packagejson: 2.5.19
    prettier-plugin-solidity: 2.1.0
    prettier-plugin-tailwindcss: 0.6.8
    semver: ^7.5.4
    string-format: ^2.0.0
    toml: ^3.0.0
    ts-jest: ^29.3.1
    tsup: ^8.4.0
    tsx: ^4.19.3
    turbo: ^2.4.4
    typescript: ^5.8.2
    vitest: ^3.2.3
    zod: 4.3.5
    zx: ^8.8.5
  onesig-solana:
    '@coral-xyz/anchor': ^0.30.1
    '@metaplex-foundation/mpl-toolbox': ^0.10.0
    '@metaplex-foundation/umi': ~1.1.1
    '@metaplex-foundation/umi-bundle-defaults': ~1.1.1
    '@metaplex-foundation/umi-eddsa-web3js': ~1.1.1
    '@metaplex-foundation/umi-program-repository': ~1.1.1
    '@metaplex-foundation/umi-web3js-adapters': ~1.1.1
  paxos-cross-chain:
    ethers: 5.7.2
  paxos-token:
    ethers: 5.7.2
  proxy-v4:
    ethers: 5.7.2
  react19:
    '@types/react': 19.2.6
    '@types/react-dom': 19.2.3
cleanupUnusedCatalogs: true
disallowWorkspaceCycles: true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - '@layerzerolabs/*'
onlyBuiltDependencies:
  - '@swc/core'
  - bufferutil
  - esbuild
  - utf-8-validate
