use anchor_lang::prelude::error_code;

#[error_code]
pub enum OneSigError {
    InvalidSignersLen,
    DuplicateSigners,
    InvalidThreshold,
    ThresholdExceedsSigners,
    MissingSigner,
    SignatureDataSizeMismatch,
    InsufficientSignatures,
    InvalidSignatureFormat,
    FailedSignatureRecovery,
    InvalidProof,
    ExpiredMerkleRoot,
    ExcessiveBalanceDeduction,
    InvalidSignerOwner,
    NonEmptySignerData,
    MissingMerkleRootState,
    MerkleRootNotCloseable,
    Reentrancy,
    InvalidRentPayer,
    SeedMismatch,
    InvalidExecutorsLen,
    DuplicateExecutor,
    ExecutorNotFound,
    ExecutorRequired,
    InvalidSigner,
    InvalidExecutor,
    ExpiredSignerExecutionProof,
    SignerExecutionProofUnauthorized,
    MissingProgramId,
    NonceMutatedDuringExecution,
}
