[profile.default]
solc = '0.8.22'
verbosity = 3
src = "contracts"
test = "test"
out = "artifacts"
cache_path = "cache"
libs = ['node_modules', 'node_modules/@layerzerolabs/toolbox-foundry/lib']
optimizer = true
optimizer_runs = 200

remappings = [
    'ds-test/=node_modules/@layerzerolabs/toolbox-foundry/lib/ds-test/',
    'forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@layerzerolabs/=node_modules/@layerzerolabs/',
]

[fuzz]
runs = 1000
